const AppConstants = new Map([
  ["SCROLL_UP", "UP"],
  ["SCROLL_DOWN", "DOWN"],
  ["GUTHUB_LINK", "https://github.com/SalmanMujtaba"],
  ["TWITTER_LINK", "https://twitter.com/salman17931"],
  ["LINKEDIN_LINK", "https://www.linkedin.com/in/salman-mujtaba/"],
  ["FACEBOOK_LINK", "https://www.facebook.com/salman.mujtaba.98"],
  ["EXPENSIFY_APP_LINK", "https://github.com/SalmanMujtaba/React-Expensify-App"],
  ["TWITTER_LINK", "https://twitter.com/salman17931"],
  ["FACEBOOK_LINK", "https://www.facebook.com/salman.mujtaba.98"],
  ["AREAS_HEADING", "Areas of interest"],
  ["AREAS_SUB_HEADING", "Take a look at what I am enthused about"],
  ["ANGULAR_LABEL", "Angular"],
  ["REACT_LABEL", "React"],
  ["MATERIAL_LABEL", "Material"],
  ["JAVASCRIPT_LABEL", "Javascript"],
  ["NODE_LABEL", "Node"],
  ["NEXT_LABEL", "Next"],
  ["NEST_LABEL", "Nest"],
  ["HTML_LABEL", "HTML"],
  ["FACEBOOK_LABEL", "Facebook"],
  ["TWITTER_LABEL", "Twitter"],
  ["INSTAGRAM_LABEL", "Instagram"],
  ["DATABASE_LABEL", "Database"],
  ["CSS_LOGO_LABEL", "CSS"],
  ["GEAR_LABEL", "Gear"],
  ["ALBUM_SEARCH_IMG", "AlbumSearch"],
  ["ALBUM_SEARCH_IMG_MOBILE", "AlbumSearchMobile"],
  ["VERCEL_LABEL", "Vercel"],
  ["SCSS_LOGO_LABEL", "SCSS"],
  ["KARMA_LABEL", "Karma"],
  ["GITHUB_LABEL", "GitHub"],
  ["API_LABEL", "API"],
  ["TS_LABEL", "Typescript"],
  ["GIHUB_VIDEO", "GithubVideo"],
  ["STAR_ICON_LABEL", "Star"],
  ["BOLT_ICON_LABEL", "Bolt"],
  ["LINK_ICON_LABEL", "Link"],
  ["CODE_ICON_LABEL", "Code"],
  ["RIGHT_ICON_LABEL", "Right"],
  ["ANGULAR_ICON_LINK", "../../../assets/icons/angular-logo.svg"],
  ["REACT_ICON_LINK", "../../../assets/icons/angular-logo.svg"],
  ["JAVASCRIPT_ICON_LINK", "../../../assets/icons/javascript-logo.svg"],
  ["NEST_ICON_LINK", "../../../assets/icons/nestjs-logo.svg"],
  ["NEXT_ICON_LINK", "../../../assets/icons/nextjs-logo.svg"],
  ["REACT_ICON_LINK", "../../../assets/icons/react-logo.svg"],
  ["NODE_ICON_LINK", "../../../assets/icons/icons8-node-js.svg"],
  ["DATABASE_ICON_LINK", "../../../assets/icons/database-icon.png"],
  ["HTML_ICON_LINK", "../../../assets/icons/html-logo.svg"],
  ["CSS_ICON_LINK", "../../../assets/icons/css3-logo.svg"],

]
);

export default AppConstants;